language: node_js
node_js:
- 16.13.2
install:
- npm ci
jobs:
  include:
  - stage: travis test
    scripts:
    - echo 'test'
env:
  global:
    secure: aMgBi/Agk6orUlM/CsAxYajGtkOoPuOyOO1E+noBPn9lQ6bZauIHP2nn/s69mUcZHA9+K2f6Hgi1hXKrzcMKweMB2J2nH2epAPquv420z/pzC+5r7HPstFuEIuO4y0DZRrEkfYxQ2gAD9VIal710RlG2ovIecX6rvA9GoPkZoUDW1gGNe9AF4fq4TYxxGZth27Iy5kvbONj4xFiwAKfwFHEQ/Wv8y5HDS8EnClB15Ke+tAeKSRsldv2njcTb6iVZtsBdxgYXthWsHE3RBItuf5mbbrRVp3FFyWtVOXrEHutMk0dDqVVAqKHlFQ76Nx6c77Jz21kZVmyUGZJkLZL0WhzTFD0bKchUktdNvv7rbXKpCEO8xnJjUavmr4KRZXYAI6iMiQQIZqS5NhehNWd0V9ZL9sXDx2VyI7aBl4gfE+Eh1714hUyX7FlhXMy8eScynth1fNU1yTxSpLtFRM2dGRGNnBBoBq8pd7C/lit2Lhz3mTUWt0cSijPp6t8AKO+2+rDCkSzqKVntvKJqlisbjVX2RGqRo3hYTwq2L/5ql1mJYkyCVR8l7gQIZQcflyelkny0A63vcmPDrQiDlm9rOWQ7j65YY/oJr7/qWRcYkj/HgSFHbJNOzRNaAqynN3VPvdNTH0D2tq2fTJ+/03zDrFnGYfoP0X13nxS3oEpF4Vw=
