language: node_js
node_js:
- 16.13.2
install:
- npm ci
addons:
  sonarcloud:
    organization: xpfarmrepositories-tobyschaeffer
    token:
      secure: phVOJ/VdjFklHXU4sfLY9hrW307Klyvz71b/gSSFtcNxrehbDwp4oyKQoEbMJ13IFx7KqGpeDwHbkWe1BdL5bAAGj4jmgLQhnzTrnjER5Epwn7P4kaNnc7gDzuXkECvqaQ8iIrt8qPPDp+3TRpF6ljsu6w4ZBi7OJKh0bUaQBLJQVTipwkD6wfsH2DUiFWvB0wwAv0OgjsjTCcuPI8e0GWioIkgi8VfCkTBQofEYBLHP+A9fjbGbm1p46dilRF3vIHW/ZMg56ily6JWdNmSfQSVJXcnC+xHPH5+xInGDkPL8wBi8CwAC+OxVAaV4g3tqcVYPz5SplpdR72lHiM3W12tbJxO57hJu6zM58k0ALl+VDN/vcUgj+oo1yzRqMrkiGsm8SheV8tFGeLdiPQYJiLExrcY3TWEKLVgZHWISflXsEBR53s7pd52hE38jPnLy7xVzl0gIFrV5vEF+6cBiS6kJgQkgNIQEGviRQMw8VmLLTnasW572V/cGy3HuKwnQGDbzX9HEsPwobo4dMIobv9uriXkPyJ7TXGlNp4dP4nZZAvDpOX5ZskpO5GkF7mF8eUwbp4tgb3GgqlojM81CghV3kj/S7igZMx4PAOX4TcbbZpf2gG+dODG65aiRHJ0gppkijF9Ih+2hG/NTg9aV2qqIKpNPTB/SI4WMbOnctqs=
jobs:
  include:
  - stage: snyk dev tests and unit tests
    scripts:
    - npm run test
  - stage: run Sonar-Scanner
    script:
    - sonar-scanner
env:
  global:
  - secure: vWiH7itHPqwpGLIvLlmz8GBRMaAoVtxcNemff7nt3ylQhWwbfX6TyixyrJ3yc6LfyzcUkV+/8ukov3hu3TychTKVALw6r9m0RR8WlC51R6J6+rylK/yTw1ya9VoDd0Vm+7l6w23nFZz4A5814P9JxbkKoC7MMcQL3h/mSqZlD1emhJZ6jkWE+GxfJkHTD+Wa5fn6XkqkljvBCwn23GaI9qZczlD1DHgyVlRZKGXSMN6V+qzUc038xbNLqdyDs7hgHUemle4yeL4WsWWXDpCUtofcqmoPvbR4OjmghvUuv5I+XqNdfjY3WCgYvXbGwziCoa/5YJK6B7u0gnh+UaBwA6VuOdcKmkXztZlh0osSXVIzkp5bWqMPoabFYsj1KtQB3U7G/YH807DVXg+VOvj8QxHZOXPN3GZVC7It2bxPVvWkPOdXXYkL8tECKDeI6rqjXemF8aj4wDfruvhkSbrxFyUypncZg4vkPGT/9Tp38a5DMEKGl2WFKRken/QBu+AFLCG9lJL7cneRQO14/5eWyfMWJo0bHLpWjlZ0daAAkzbjsykOZg9dOTxmlX0lAoCENWuD+OQnee9kmVyvGYTz/6nYgWAIrU6R51qNjdehWFAtCv3bw5tLKexIfif5RaCYwlpRflRyOElpZ0Q8/AxWcJ4NBXgTypp6NzgILcIAOns=
  - secure: phVOJ/VdjFklHXU4sfLY9hrW307Klyvz71b/gSSFtcNxrehbDwp4oyKQoEbMJ13IFx7KqGpeDwHbkWe1BdL5bAAGj4jmgLQhnzTrnjER5Epwn7P4kaNnc7gDzuXkECvqaQ8iIrt8qPPDp+3TRpF6ljsu6w4ZBi7OJKh0bUaQBLJQVTipwkD6wfsH2DUiFWvB0wwAv0OgjsjTCcuPI8e0GWioIkgi8VfCkTBQofEYBLHP+A9fjbGbm1p46dilRF3vIHW/ZMg56ily6JWdNmSfQSVJXcnC+xHPH5+xInGDkPL8wBi8CwAC+OxVAaV4g3tqcVYPz5SplpdR72lHiM3W12tbJxO57hJu6zM58k0ALl+VDN/vcUgj+oo1yzRqMrkiGsm8SheV8tFGeLdiPQYJiLExrcY3TWEKLVgZHWISflXsEBR53s7pd52hE38jPnLy7xVzl0gIFrV5vEF+6cBiS6kJgQkgNIQEGviRQMw8VmLLTnasW572V/cGy3HuKwnQGDbzX9HEsPwobo4dMIobv9uriXkPyJ7TXGlNp4dP4nZZAvDpOX5ZskpO5GkF7mF8eUwbp4tgb3GgqlojM81CghV3kj/S7igZMx4PAOX4TcbbZpf2gG+dODG65aiRHJ0gppkijF9Ih+2hG/NTg9aV2qqIKpNPTB/SI4WMbOnctqs=
